{{- with .Values.eunomia.operator }}
{{- if not .deployment.nsRbacOnly -}}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ''
  name: {{ .namespace }}
spec:
{{- end }}
{{- end }}
