{{- with .Values.eunomia.operator }}
{{- if and .openshift.route.enabled (not .deployment.nsRbacOnly) -}}
apiVersion: v1
kind: Route
metadata:
  name: eunomia-operator
  namespace: "{{ .namespace }}"
spec:
  port:
    targetPort: webhook  
  to:
    kind: Service
    name: eunomia-operator
{{- end }}
{{- end }}
